from . import account_move
from . import import_attendance
from . import import_bill_of_material
from . import import_invoice
from . import import_payment
from . import import_task
from . import import_pos_order
from . import import_purchase_order 
from . import wizard_producto
from . import contact_import_wizard
from . import import_message 
